[package]
name = "rust-game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[[bin]]
name = "game"
path = "src/0-game.rs"

[[bin]]
name = "primitive"
path = "src/1-primitive.rs"

[[bin]]
name = "array"
path = "src/2-array.rs"
